### ISSUE TITLE
idea: nuget package?

### ISSUE THREAD

**Issue by benkoshy** [gileCAD/GeometryExtensions#5]
Hey Gilles

Thanks for publishing your library. 

Would it be a ridiculous idea to [publish it as a Nuget Package](https://learn.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?tabs=netcore-cli)?

(btw always appreciated your knowledge etc on the forums.)

Ben

**Comment by gileCAD** [comment]
I hadn't considered that before, but I'll think about it when I have some free time.

**Comment by benkoshy** [comment]
Pls LMK (let me know) what you think. I can provide PRs (pull requests) for this.

**Comment by benkoshy** [comment]
Closed with https://github.com/gileCAD/GeometryExtensions/issues/6
