### ISSUE TITLE
PRs for other extension methods?

### ISSUE THREAD

**Issue by benkoshy** [gileCAD/GeometryExtensions#6]
Hi Gilles, 

Would you object to PRs for extension methods to other classes?

Pls LMK.

**Comment by gileCAD** [comment]
Could you please clarify, as I am not sure I fully understand what you mean (English is not my first language).

**Comment by gileCAD** [comment]
For sure you can create pull requests.

**Comment by benkoshy** [comment]
(As a side note: I would recommend opening up the discussion board to ease the maintenance burden. Thank you for your feedback / response.)
